# -*- coding: utf-8 -*-
"""WEEK-5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QfUTdNSWemWwHLY88BIFu_LXtUlUYDkU
"""

import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
import seaborn as sns

np.random.seed(42)

n = 10000

df = pd.DataFrame({
    "Patient_ID": range(1, n+1),
    "Age": np.random.randint(20, 81, n),
    "Gender": np.random.choice(["Male", "Female"], n),
    "Blood_Pressure": np.random.randint(80, 181, n),
    "Sugar_Level": np.random.randint(70, 201, n),
    "Cholesterol": np.random.randint(150, 301, n),
    "Heart_Rate": np.random.randint(60, 121, n)
})

print(df.head())

print(df.isnull().sum())

df.fillna(df.mean(numeric_only=True), inplace=True)

print(df.dtypes)

# Range validation
df = df[(df["Age"] >= 20) & (df["Age"] <= 80)]
df = df[(df["Blood_Pressure"] >= 80) & (df["Blood_Pressure"] <= 180)]
df = df[(df["Sugar_Level"] >= 70) & (df["Sugar_Level"] <= 200)]
df = df[(df["Cholesterol"] >= 150) & (df["Cholesterol"] <= 300)]
df = df[(df["Heart_Rate"] >= 60) & (df["Heart_Rate"] <= 120)]

# Standardize Gender values
df["Gender"] = df["Gender"].str.strip().str.capitalize()
df = df[df["Gender"].isin(["Male", "Female"])]

# Ensure correct data types
df = df.astype({
    "Age": int,
    "Blood_Pressure": int,
    "Sugar_Level": int,
    "Cholesterol": int,
    "Heart_Rate": int
})

# Remove duplicate Patient IDs
df = df.drop_duplicates(subset="Patient_ID")

print(df.mean(numeric_only=True))

print(df.median(numeric_only=True))

print(df.mode().iloc[0])

print(df.std(numeric_only=True))

print(df["Blood_Pressure"].describe())

print(df["Sugar_Level"].describe())

print(df["Cholesterol"].describe())

print(df["Heart_Rate"].describe())

def classify_risk(row):
    if (row["Blood_Pressure"] > 140 or
        row["Sugar_Level"] > 180 or
        row["Cholesterol"] > 240):
        return "High"
    elif (row["Blood_Pressure"] > 120 or
          row["Sugar_Level"] > 140 or
          row["Cholesterol"] > 200):
        return "Medium"
    else:
        return "Low"

df["Risk_Level"] = df.apply(classify_risk, axis=1)

print(df["Risk_Level"].value_counts())

high_risk = df[df["Risk_Level"] == "High"]

print(high_risk.head())
print("Total High Risk:", len(high_risk))

df["Age_Group"] = pd.cut(df["Age"],
                        bins=[20,30,40,50,60,70,80],
                        labels=["20-30","30-40","40-50","50-60","60-70","70-80"])

print(df.groupby("Age_Group")["Risk_Level"].value_counts())

print(df.groupby("Gender")["Risk_Level"].value_counts())

print(df["Risk_Level"].value_counts())

print(df[["Age", "Blood_Pressure"]].corr())

print(df[["Cholesterol", "Heart_Rate"]].corr())

print(df.groupby("Risk_Level")["Sugar_Level"].mean())

import matplotlib.pyplot as plt
import seaborn as sns

df["Risk_Level"].value_counts().plot(kind="bar")
plt.title("Risk Level Distribution")
plt.show()

df["Risk_Level"].value_counts().plot(kind="pie", autopct='%1.1f%%')
plt.show()

df["Age"].hist()
plt.title("Age Distribution")
plt.show()

plt.scatter(df["Age"], df["Blood_Pressure"])
plt.xlabel("Age")
plt.ylabel("Blood Pressure")
plt.show()

sns.boxplot(x=df["Cholesterol"])
plt.show()

corr = df.corr(numeric_only=True)

sns.heatmap(corr, annot=True)
plt.show()

print("High Risk Patients %:", (len(high_risk)/len(df))*100)

print(df.groupby("Risk_Level").mean(numeric_only=True))

print("Most Common Risk:", df["Risk_Level"].mode()[0])

print("Successfully")